apiVersion: v1
kind: Service
metadata:
  name: merge-sort
  namespace: default
spec:
  selector:
    app: merge-sort
  type: NodePort    
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000