---
apiVersion: v1
kind: Pod
metadata:
  name: merge-sort-pod
  labels:
    app: merge-sort
spec:
  containers:
    - name: merge-sort-app
      image: merge-sort
      imagePullPolicy: Never
      env:
        - name: TZ
          value: America/Tijuana
      ports:
        - containerPort: 8080