apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-curl
        image: curlimages/curl:7.84.0
        command:         
        - "bin/sh"
        - "-c"        
        - "echo \"1. Probando merge-sort-service: \"; curl http://merge-sort-service:8080/api; 
          echo -e \"\n2. Probando merge-sort-service: \"; curl http://merge-sort-service:8080/api;"
      restartPolicy: Never
  backoffLimit: 4